# Documentation here https://circleci.com/developer/orbs/orb/later/ruby-rails-setup
# Following tutorial https://thoughtbot.com/blog/circleci-2-rails

version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2
  ruby-rails-setup: later/ruby-rails-setup@0.0.3

jobs:
  build:
    working_directory: ~/compost-lyon
    docker:
      - image: circleci/ruby:2.6.3-node-browsers
        environment:
          PGHOST: localhost
          PGUSER: CompostLyon
          RAILS_ENV: test
          RACK_ENV: test
          NODE_ENV: test
      - image: postgres:9.5
        environment:
          POSTGRES_USER: CompostLyon
          POSTGRES_DB: CompostLyon_test
          POSTGRES_PASSWORD: <%= ENV['COMPOSTLYON_DATABASE_PASSWORD'] %>
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Configure Bundler
          command: |
              echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
              source $BASH_ENV
              gem install bundler

      # Bundle install dependencies
      - run: bundle install
      - run: yarn install
      - run: bin/rails webpacker:compile
      - save_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}-{{ checksum "yarn.lock" }}
          paths:
            - vendor/bundle
            - public/packs-test
      # Setup the database
      - run: bundle exec rake db:drop RAILS_ENV=test
      - run: bundle exec rake db:create RAILS_ENV=test
      - run: bundle exec rake db:schema:load RAILS_ENV=test

      # --- RSPEC

      - run:
          name: Running tests
          command: bundle exec rspec
